import './globals.css';
import { Poppins } from 'next/font/google';
import Sidebar from '@/components/Sidebar';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Global Portfolio Tracker',
  description: 'Generated by create next app',
};

const SIDEBAR_WIDTH = 274;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex h-screen bg-neutral-50`}>
        <Sidebar width={SIDEBAR_WIDTH} />
        <div style={{ marginLeft: SIDEBAR_WIDTH }} className="p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
