import './globals.css';
import { Poppins } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';
import { CurrencyProvider } from '@/contexts/CurrencyContext';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Global Portfolio Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex h-screen w-screen bg-neutral-50`}>
        <CurrencyProvider>
          <Sidebar />
          <div className="flex flex-1 flex-col overflow-x-hidden">
            <Header />
            {children}
          </div>
        </CurrencyProvider>
      </body>
    </html>
  );
}
